### ISSUE TITLE
_predict_loop error

### ISSUE THREAD

**Issue by hosniehpanahandeh** [cyprienruffino/CTCModel#10]
Hello,
I am trying to run ctcmodel with its dataset, but I got this error during running predict_loop function:
**TypeError: Cannot convert 0.0 to EagerTensor of dtype int32**
this error raise from line `batch_outs = f(ins_batch)`
and because of [0.] added to x in predict function.
I replaced  [ins[-1]] at line ' ins_batch = _slice_arrays(ins[:-1], batch_ids) + [ins[-1]]' with [0] but then i got empty array in the result of prediction.

I use tensorflow 2, maybe it brings problems here, because i made no changes in CTCmodel.py and example.py.
I just tried to run it.

thanks in advance.

**Comment by hosniehpanahandeh** [comment]
I downgraded my tensorflow to 1.15 and i got null as the result of prediction:
Prediction : []  -- Label :  [3. 3. 1. 4.]
Prediction : []  -- Label :  [1. 1.]
Prediction : []  -- Label :  [0. 7. 2.]
Prediction : []  -- Label :  [6. 4.]
Prediction : []  -- Label :  [5. 8.]
Prediction : []  -- Label :  [0. 6. 9.]
Prediction : []  -- Label :  [6. 8. 6. 6.]
Prediction : []  -- Label :  [4. 1.]
Prediction : []  -- Label :  [8. 4.]
Prediction : []  -- Label :  [2. 3. 3. 1.]

**Comment by alexandrucosminmihai** [comment]
Hello!

Did you run the training for the default 10 epochs? If not, try increasing the number of epochs you're training for. I had a similar problem while trying the example, but using the default number of epochs (10) ended up providing good results.

**Comment by hamdanihamza** [comment]
Hello am having the same problem... I am training on 20 epochs and the predictions returned are all empty

**Comment by cyprienruffino** [comment]
See Issue #12
