### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by adityajain07** [cyprienruffino/CTCModel#15]
Hello, 

I successfully installed this library using pip but it fails to import: ModuleNotFoundError: No module named 'keras_ctcmodel.CTCModel'

When I check the directory of pip library installations, only this file is there for ctc: keras_ctcmodel-1.1.0.dist-info. The complete library doesn't seem to be installed. 

I even tried manually building but no luck. Did anyone face a similar issue?

**Comment by cyprienruffino** [comment]
Hi ! 
There is indeed a problem with the egg file on Pypi. I'll repackage it as soon as possible.
In the meantime, you can clone the github and run the setup.py with
$ python setup.py install --user
I've just tested it and it works.

Thanks for the report !
