### ISSUE TITLE
loaded model can not work well

### ISSUE THREAD

**Issue by JohnLoveMm** [cyprienruffino/CTCModel#16]
Hi,when i load the trained model,it can not work well.i used `loaded=CTCModel(None,None),loaded.load_model(path, optimizer)` to load my model,and,`loaded.predict([x_test_pad, x_test_len], batch_size, max_value)` to get the prediction,  but it can not work well ,just like a did not trained model,the prediction was absolutely wrong.I do not know how to deal with it, could you please help me?

**Comment by cyprienruffino** [comment]
That's weird, I'll check that out.
Can you send me the weights of your model, if you can ?

**Comment by JohnLoveMm** [comment]
In fact,I can not find the weights file,in my path folder,there are only five files,they are("model_eval.json","model_init.json","model_param.pkl","model_pred.json","model_train.json"),there was no weights of my model,I do not know how to load the weights.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cyprienruffino/CTCModel"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 晚上7:48
收件人:&nbsp;"cyprienruffino/CTCModel"<CTCModel@noreply.github.com&gt;;
抄送:&nbsp;"🐶"<1140063996@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cyprienruffino/CTCModel] loaded model can not work well (#16)





 
That's weird, I'll check that out.
 Can you send me the weights of your model, if you can ?

**Comment by cyprienruffino** [comment]
Wow you're right, the weights aren't saved anymore ! How in the hell did that slipped under the radar ?!
I'm fixing that immediatly

**Comment by JohnLoveMm** [comment]
Thank you for paying so much attention to my feedback and looking forward to your update。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cyprienruffino/CTCModel"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 晚上9:58
收件人:&nbsp;"cyprienruffino/CTCModel"<CTCModel@noreply.github.com&gt;;
抄送:&nbsp;"🐶"<1140063996@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cyprienruffino/CTCModel] loaded model can not work well (#16)





 
Wow you're right, the weights aren't saved anymore ! How in the hell did that slipped under the radar ?!
 I'm fixing that immediatly

**Comment by cyprienruffino** [comment]
Boom, done !
I pushed on master and re-published on pypi.
It should save (and load) the weights correctly, as model_weights.hdf5.
Sorry for this issue. Could you re-install CTCModel and try it ?

**Comment by JohnLoveMm** [comment]
Now, I can load my model easily,thank you very much.But the loaded model's prediction("loaded.predict") did not same as the "network.predict" after training,I do not know the reason.I will tell you the final result,it will cost 4 days.&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cyprienruffino/CTCModel"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 晚上10:30
收件人:&nbsp;"cyprienruffino/CTCModel"<CTCModel@noreply.github.com&gt;;
抄送:&nbsp;"🐶"<1140063996@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cyprienruffino/CTCModel] loaded model can not work well (#16)





 
Boom, done !
 I pushed on master and re-published on pypi.
 It should save (and load) the weights correctly, as model_weights.hdf5.
 Sorry for this issue. Could you re-install CTCModel and try it ?

**Comment by JohnLoveMm** [comment]
> Boom, done !
> I pushed on master and re-published on pypi.
> It should save (and load) the weights correctly, as model_weights.hdf5.
> Sorry for this issue. Could you re-install CTCModel and try it ?

oh,I find the reason,we should save the weights of model_pred,rather than model_train.or we can save all of the weights,when we load,we can chose which one we need.and i want know what is use of weights of model_train,model_eval,model_init ,could you please tell me?
