### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType

### ISSUE THREAD

**Issue by neenaloysius** [cyprienruffino/CTCModel#17]
X_train_len = Input(name='input_length', shape=X_train_length.shape[0], dtype=dtype)  # unpadded len of all x_sequences in batch
Y_train_len =Input(name='label_length', shape=label_length.shape[0], dtype=dtype)  # unpadded len of all y_sequences in batch
y_train=np.ndarray(shape=(num_files,max_y_length),
                     dtype=np.float32)
y_train.fill(1)
##X_train shape is (3,208,224,224,3)
model.fit(x=[X_train,y_train,X_train_len,Y_train_len], y=np.ones((208,30)), batch_size=1)

Im getting error "TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'"
Not sure which argument is causing the issue.

**Comment by cyprienruffino** [comment]
Hi !
I'm sorry for not handling that earlier, I'm really busy writing my Phd thesis right now.
I'll try to provide a solution as quickly as I can.
