### ISSUE TITLE
Problem in transfer learning

### ISSUE THREAD

**Issue by Sanskar777** [cyprienruffino/CTCModel#18]
Hi,

I am trying to use this model for doing the following-
1. Fine tune the model further by loading a previously saved model: I am not understanding how to access the layers individually as model.get_layers('layer_name') isn't working. I am trying to add dropout layers in between the layers of the previously saved model.
2.  I am trying to further add more layers at the end by removing the Dense layer at the end: The include_top parameter doesn't seem to work
Could you please provide this functionality(specially point 1) or guide me how to do so.

**Comment by cyprienruffino** [comment]
Hi ! 
I'm sorry for not handling that earlier, I'm really busy writing my Phd thesis right now.
I'll try to provide a solution as quickly as I can.
