### ISSUE TITLE
AttributeError: pred = network.predict([x_test_pad, x_test_len])

### ISSUE THREAD

**Issue by Hossein-Gholami** [cyprienruffino/CTCModel#3]
Hi
I was trying to explore the example and everything works fine but the last lines:

`# predict label sequences

pred = network.predict([x_test_pad, x_test_len], batch_size=batch_size, max_value=padding_value)

for i in range(10):  # print the 10 first predictions
    print("Prediction :", [j for j in pred[i] if j!=-1], " -- Label : ", y_test[i])`

face the following error:

`AttributeError                            Traceback (most recent call last)
<ipython-input-12-2d250febd9d0> in <module>()
      1 # predict label sequences
      2 #pred = network.predict([x_test_pad, x_test_len], batch_size=batch_size, max_value=padding_value)
----> 3 pred = network.predict([x_test_pad, x_test_len])
      4 for i in range(10):  # print the 10 first predictions
      5     print("Prediction :", [j for j in pred[i] if j!=-1], " -- Label : ", y_test[i])

~/Workspace/jupyter/Speech/CTCModel/CTCModel.py in predict(self, x, batch_size, verbose, steps, max_len, max_value)
    737         f = self.model_pred.predict_function
    738         out = self._predict_loop(f, ins, batch_size=batch_size, max_value=max_value,
--> 739                                   verbose=verbose, steps=steps, max_len=max_len)
    740 
    741         out_decode = [dec_data[:list(dec_data).index(max_value)] if max_value in dec_data else dec_data for i,dec_data in enumerate(out)]

~/Workspace/jupyter/Speech/CTCModel/CTCModel.py in _predict_loop(self, f, ins, max_len, max_value, batch_size, verbose, steps)
    761             (if the model has multiple outputs).
    762         """
--> 763         num_samples = self.model_pred._check_num_samples(ins, batch_size,
    764                                               steps,
    765                                               'steps')

AttributeError: 'Model' object has no attribute '_check_num_samples'`

**Comment by danieltanasec** [comment]
Get the Gitlab version and it will work
https://git.litislab.fr/TextRecognition/CTCModel/tree/master

**Comment by Hossein-Gholami** [comment]
@Tzuya14 Thank you a lot

**Comment by hamdanihamza** [comment]
Hello sir I got the same problem but with the `uses_learning_phase `attribute. the both version are not working ! Any suggestions ? like which version of keras and tf I should use ?
